namespace vcxproj2cmake;

record QtModule(string ModuleName, string CMakeComponentName, string CMakeTargetName);

class QtModuleInfoRepository
{
    public static QtModule GetQtModuleInfo(string moduleName, int qtVersion)
    {
        if (!qtModuleToCMakeComponentName.TryGetValue(moduleName, out var cmakeComponentName))
            throw new CatastrophicFailureException($"Unknown Qt module: {moduleName}");

        return new QtModule(moduleName, cmakeComponentName, $"Qt{qtVersion}::{cmakeComponentName}");
    }

    static readonly Dictionary<string, string> qtModuleToCMakeComponentName = new()
    {
        { "3danimation",        "3DAnimation" },
        { "3dcore",             "3DCore" },
        { "3dextras",           "3DExtras" },
        { "3dinput",            "3DInput" },
        { "3dlogic",            "3DLogic" },
        { "3dquick",            "3DQuick" },
        { "3dquickanimation",   "3DQuickAnimation" },
        { "3dquickextras",      "3DQuickExtras" },
        { "3dquickinput",       "3DQuickInput" },
        { "3dquickrender",      "3DQuickRender" },
        { "3dquickscene2d",     "3DQuickScene2D" },
        { "androidextras",      "AndroidExtras" },
        { "axcontainer",        "AxContainer" },
        { "axserver",           "AxServer" },
        { "bluetooth",          "Bluetooth" },
        { "charts",             "Charts" },
        { "coap",               "Coap" },
        { "concurrent",         "Concurrent" },
        { "core",               "Core" },
        { "core5compat",        "Core5Compat" },
        { "datavisualization",  "DataVisualization" },
        { "dbus",               "DBus" },
        { "gamepad",            "Gamepad" },
        { "graphicaleffects",   "GraphicalEffects" },
        { "graphs",             "Graphs" },
        { "grpc",               "Grpc" },
        { "gui",                "Gui" },
        { "help",               "Help" },
        { "httpserver",         "HttpServer" },
        { "imageformats",       "ImageFormats" },
        { "location",           "Location" },
        { "lottieanimation",    "LottieAnimation" },
        { "macextras",          "MacExtras" },
        { "mqtt",               "Mqtt" },
        { "multimedia",         "Multimedia" },
        { "multimediawidgets",  "MultimediaWidgets" },
        { "network",            "Network" },
        { "networkauth",        "NetworkAuth" },
        { "nfc",                "Nfc" },
        { "opcua",              "OpcUa" },
        { "opengl",             "OpenGL" },
        { "openglwidgets",      "OpenGLWidgets" },
        { "pdf",                "Pdf" },
        { "platformheaders",    "PlatformHeaders" },
        { "positioning",        "Positioning" },
        { "printsupport",       "PrintSupport" },
        { "protobuf",           "Protobuf" },
        { "purchasing",         "Purchasing" },
        { "qml",                "Qml" },
        { "qmlcompiler",        "QmlCompiler" },
        { "quick",              "Quick" },
        { "quick3d",            "Quick3D" },
        { "quick3dassetimport", "Quick3DAssetImport" },
        { "quick3dphysics",     "Quick3DPhysics" },
        { "quickcontrols",      "QuickControls" },
        { "quickcontrols2",     "QuickControls2" },
        { "quickdialogs",       "QuickDialogs" },
        { "quickdialogs2",      "QuickDialogs2" },
        { "quickeffects",       "QuickEffects" },
        { "quicklayouts",       "QuickLayouts" },
        { "quickparticles",     "QuickParticles" },
        { "quicktest",          "QuickTest" },
        { "quicktimeline",      "QuickTimeline" },
        { "quickwidgets",       "QuickWidgets" },
        { "remoteobjects",      "RemoteObjects" },
        { "script",             "Script" },
        { "scripttools",        "ScriptTools" },
        { "scxml",              "Scxml" },
        { "sensors",            "Sensors" },
        { "serialbus",          "SerialBus" },
        { "serialport",         "SerialPort" },
        { "shadertools",        "ShaderTools" },
        { "spatialaudio",       "SpatialAudio" },
        { "sql",                "Sql" },
        { "statemachine",       "StateMachine" },
        { "svg",                "Svg" },
        { "test",               "Test" },
        { "testlib",            "Test" },
        { "texttospeech",       "TextToSpeech" },
        { "uitools",            "UiTools" },
        { "virtualkeyboard",    "VirtualKeyboard" },
        { "waylandcompositor",  "WaylandCompositor" },
        { "webchannel",         "WebChannel" },
        { "webengine",          "WebEngine" },
        { "webenginecore",      "WebEngineCore" },
        { "webenginequick",     "WebEngineQuick" },
        { "webenginewidgets",   "WebEngineWidgets" },
        { "websockets",         "WebSockets" },
        { "webview",            "WebView" },
        { "widgets",            "Widgets" },
        { "winextras",          "WinExtras" },
        { "winuiextras",        "WinExtras" },   // accepted alias
        { "x11extras",          "X11Extras" },
        { "xml",                "Xml" },
        { "xmlpatterns",        "XmlPatterns" }
    };
}
